### ISSUE TITLE
Not able to use pip to install this package

### ISSUE THREAD

**Issue by jgomo3** [jonathanj/compose#2]
This is what happens when I try to do it:

``` zsh
➜  ~   pip install compose
Collecting compose
  Could not find a version that satisfies the requirement compose (from versions: )
No matching distribution found for compose
```

**Comment by jonathanj** [comment]
@jgomo3 The `compose` project on pypi is private and different project to this one. Personally I just use [toolz](https://pypi.python.org/pypi/toolz) now, it contains `compose` and several other useful functional tools.

I think I should delete the project to avoid any future confusion.

**Comment by jgomo3** [comment]
@jonathanj Why?. Confusion with what?. I'm using it.

**Comment by jgomo3** [comment]
Thank you for referring to toolz. You don't need to delete the repo. Just redirect people to toolz and any other project related.

Thank you.

**Comment by jonathanj** [comment]
@jgomo3 Confusion with the private `compose` project on PyPI (my project actually exists in the PyPI test environment but not in production) that doesn't belong to me.

**Comment by jonathanj** [comment]
@jgomo3 Can I ask how you came to find my repository?

**Comment by jgomo3** [comment]
After reading: https://mathieularose.com/function-composition-in-python/ I though I wanted that compose function in my toolbox. In fact, first I was in a need for a composition function, searched for that and found the article. Then, I supussed there should be one module out there and began searching in github. After ignoring all the docker and django related repos, the first one I found was yours.

**Comment by jonathanj** [comment]
I published this package on PyPI as [compose-func](https://pypi.python.org/pypi/compose-func), to prevent anyone else from running into the same problem.

**Comment by jgomo3** [comment]
Nice.
